# H2 Database configuration
spring:
  datasource:
    url:  jdbc:h2:mem:playerdb
    driverClassName: org.h2.Driver
    username: sa
    password:
jpa:
database-platform: org.hibernate.dialect.H2Dialect
h2:
console:
enabled: true

graphql:
  servlet:
  exception-handlers-enabled:true
